import Foundation
import SwiftData

@Model
final class Reminder {
    var id: UUID = UUID()
    var title: String = ""
    var reminderTypeRaw: String = ReminderType.custom.rawValue
    var scheduledDate: Date = Date.now
    var isCompleted: Bool = false
    var linkedScanId: UUID?
    var cycleRecordID: UUID?
    var completedAt: Date?
    var isAutoGenerated: Bool = false

    init(id: UUID = UUID(), title: String, reminderType: ReminderType, scheduledDate: Date, isCompleted: Bool = false, linkedScanId: UUID? = nil, cycleRecordID: UUID? = nil, isAutoGenerated: Bool = false) {
        self.id = id
        self.title = title
        self.reminderTypeRaw = reminderType.rawValue
        self.scheduledDate = scheduledDate
        self.isCompleted = isCompleted
        self.linkedScanId = linkedScanId
        self.cycleRecordID = cycleRecordID
        self.completedAt = isCompleted ? .now : nil
        self.isAutoGenerated = isAutoGenerated
    }

    var reminderType: ReminderType { ReminderType(rawValue: reminderTypeRaw) ?? .custom }
}
