import XCTest
import SwiftData
@testable import MenoPlan

final class FertilityWindowCalculatorTests: XCTestCase {
    func testHomeShowsAbsoluteDateForSavedFuturePeriodReminder() throws {
        let calendar = Calendar.current
        let reminderDate = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 10, day: 5, hour: 9)))
        let expectedPeriod = try XCTUnwrap(calendar.date(byAdding: .day, value: 1, to: reminderDate))
        let oldReminder = Reminder(title: "Period expected tomorrow", reminderType: .periodExpected, scheduledDate: reminderDate, isAutoGenerated: true)
        XCTAssertEqual(HomeReminderTitle.display(for: oldReminder), "Period estimate · \(DateFormatting.shortDate.string(from: expectedPeriod))")
        XCTAssertTrue(HomeReminderTitle.scheduleLabel(for: oldReminder).hasPrefix("Reminder on "))

        let manual = Reminder(title: "Call my doctor tomorrow", reminderType: .custom, scheduledDate: reminderDate)
        XCTAssertEqual(HomeReminderTitle.display(for: manual), manual.title)
    }

    func testDoesNotInventCycleBeforeFirstLoggedPeriod() throws {
        let calendar = Calendar(identifier: .gregorian)
        let firstLoggedPeriod = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 8, day: 3)))
        let earlierDate = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 7, day: 15)))

        XCTAssertNil(FertilityWindowCalculator.window(
            for: earlierDate,
            lastPeriodStart: firstLoggedPeriod,
            averageCycleLength: 29,
            lutealPhaseLength: 14,
            calendar: calendar
        ))
    }

    func testWindowUsesCycleAndLutealPhase() throws {
        let calendar = Calendar.current
        let start = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 5, day: 1)))
        let today = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 5, day: 10)))
        let window = try XCTUnwrap(FertilityWindowCalculator.window(for: today, lastPeriodStart: start, averageCycleLength: 28, lutealPhaseLength: 14, calendar: calendar))

        XCTAssertEqual(window.cycleDay, 10)
        XCTAssertTrue(calendar.isDate(window.predictedOvulationDate, inSameDayAs: try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 5, day: 14)))))
        XCTAssertTrue(calendar.isDate(window.fertileStartDate, inSameDayAs: try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 5, day: 9)))))
        XCTAssertTrue(calendar.isDate(window.opkStartDate, inSameDayAs: try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 5, day: 7)))))
        XCTAssertLessThan(window.opkStartDate, window.fertileStartDate)
    }

    func testWindowAdvancesIntoCurrentCycle() throws {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(secondsFromGMT: 0)!
        let start = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 4, day: 1)))
        let today = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 5, day: 3)))
        let window = try XCTUnwrap(FertilityWindowCalculator.window(for: today, lastPeriodStart: start, averageCycleLength: 28, lutealPhaseLength: 14, projectsFutureCycles: true, calendar: calendar))

        XCTAssertTrue(calendar.isDate(window.cycleStart, inSameDayAs: try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 4, day: 29)))))
        XCTAssertEqual(window.cycleDay, 5)
    }

    func testOpenCycleRemainsAnchoredWhenPeriodIsLate() throws {
        let calendar = Calendar.current
        let start = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 8, day: 3, hour: 12)))
        let originalOvulation = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 8, day: 17, hour: 12)))
        let futureDate = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 10, hour: 12)))
        let cycle = CycleRecord(
            startDate: start,
            predictedOvulationDate: originalOvulation,
            averageCycleLengthAtStart: 29,
            lutealPhaseLengthAtStart: 14
        )

        let window = try XCTUnwrap(CycleTrackingService.window(for: futureDate, records: [cycle], settings: nil, calendar: calendar))

        XCTAssertTrue(calendar.isDate(window.cycleStart, inSameDayAs: start))
        XCTAssertEqual(window.cycleDay, 39)
        XCTAssertTrue(window.isPastExpectedPeriod(on: futureDate))
        XCTAssertTrue(calendar.isDate(window.nextPeriodDate, inSameDayAs: try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 1)))))
    }

    func testTwoYearsOfHistoryUsesRecentCyclesAndBackfilledData() throws {
        let calendar = Calendar.current
        let first = try XCTUnwrap(calendar.date(from: DateComponents(year: 2024, month: 1, day: 1)))
        var starts = [first]
        for length in Array(repeating: 28, count: 18) + [24, 35, 27, 39, 30, 36] {
            starts.append(try XCTUnwrap(calendar.date(byAdding: .day, value: length, to: starts.last!)))
        }
        let periods = starts.map { PeriodEvent(startDate: $0) }
        XCTAssertEqual(CycleTrackingService.learnedAverageCycleLength(from: periods, fallback: 28, calendar: calendar), 33)
        XCTAssertEqual(CycleTrackingService.cycleLengthVariability(from: periods, calendar: calendar), 15)

        let records = zip(starts, starts.dropFirst()).map { CycleRecord(startDate: $0, endDate: $1) }
            + [CycleRecord(startDate: starts.last!)]
        let currentDate = try XCTUnwrap(calendar.date(byAdding: .day, value: 10, to: starts.last!))
        let window = try XCTUnwrap(CycleTrackingService.window(for: currentDate, records: records, periods: periods, settings: nil, calendar: calendar))
        XCTAssertTrue(window.isIrregular)
        XCTAssertEqual(window.cycleDay, 11)
        XCTAssertTrue(calendar.isDate(window.cycleStart, inSameDayAs: starts.last!))
    }

    func testMissingRecentPeriodsDoNotPullInAncientCycleLengths() throws {
        let calendar = Calendar.current
        let first = try XCTUnwrap(calendar.date(from: DateComponents(year: 2024, month: 1, day: 1)))
        var starts = [first]
        for length in [28, 28, 28, 28, 28, 120, 120, 120, 120, 120, 120] {
            starts.append(try XCTUnwrap(calendar.date(byAdding: .day, value: length, to: starts.last!)))
        }
        let periods = starts.map { PeriodEvent(startDate: $0) }
        XCTAssertEqual(CycleTrackingService.learnedAverageCycleLength(from: periods, fallback: 34, calendar: calendar), 34)
        XCTAssertNil(CycleTrackingService.cycleLengthVariability(from: periods, calendar: calendar))
    }

    func testManualPeriodStartConflictOnlyCoversExistingBleeding() throws {
        let calendar = Calendar.current
        let start = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 7, day: 1)))
        let event = PeriodEvent(startDate: start)
        let fourthDay = try XCTUnwrap(calendar.date(byAdding: .day, value: 3, to: start))
        let tenthDay = try XCTUnwrap(calendar.date(byAdding: .day, value: 9, to: start))
        XCTAssertNotNil(CycleTrackingService.periodStartConflict(on: fourthDay, periods: [event]))
        XCTAssertNil(CycleTrackingService.periodStartConflict(on: tenthDay, periods: [event]))
        XCTAssertNotNil(CycleTrackingService.periodStartConflict(on: tenthDay, periods: [event], minimumSeparationDays: 15))
    }

    @MainActor
    func testInsertingMissedHistoricalPeriodPreservesLatestCycle() throws {
        let calendar = Calendar.current
        let june = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 6, day: 7, hour: 12)))
        let july = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 7, day: 7, hour: 12)))
        let august = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 8, day: 3, hour: 12)))
        let settings = UserSettings()
        settings.lastPeriodStartDate = august
        let juneCycle = CycleRecord(startDate: june, endDate: august, status: .completed)
        let augustCycle = CycleRecord(startDate: august)
        let periods = [PeriodEvent(startDate: june, cycleRecordID: juneCycle.id), PeriodEvent(startDate: august, cycleRecordID: augustCycle.id)]
        let configuration = ModelConfiguration(isStoredInMemoryOnly: true)
        let container = try ModelContainer(for: UserSettings.self, CycleRecord.self, PeriodEvent.self, configurations: configuration)
        let context = ModelContext(container)
        context.insert(settings)
        context.insert(juneCycle)
        context.insert(augustCycle)
        periods.forEach(context.insert)

        let inserted = CycleTrackingService.recordPeriodStart(july, settings: settings, records: [juneCycle, augustCycle], periods: periods, context: context, calendar: calendar)

        XCTAssertEqual(inserted.status, .completed)
        XCTAssertTrue(calendar.isDate(try XCTUnwrap(inserted.endDate), inSameDayAs: august))
        XCTAssertTrue(calendar.isDate(try XCTUnwrap(juneCycle.endDate), inSameDayAs: july))
        XCTAssertTrue(calendar.isDate(try XCTUnwrap(settings.lastPeriodStartDate), inSameDayAs: august))
    }

    func testProjectionHorizonStopsAfterSixMonths() throws {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(secondsFromGMT: 0)!
        let anchor = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 8, day: 3)))
        let limit = try XCTUnwrap(calendar.date(from: DateComponents(year: 2027, month: 2, day: 3)))
        let beyond = try XCTUnwrap(calendar.date(from: DateComponents(year: 2027, month: 2, day: 4)))

        XCTAssertTrue(FertilityWindowCalculator.isWithinProjectionHorizon(limit, from: anchor, calendar: calendar))
        XCTAssertFalse(FertilityWindowCalculator.isWithinProjectionHorizon(beyond, from: anchor, calendar: calendar))
    }

    func testCycleDayRemainsCorrectAcrossDaylightSavingChange() throws {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = try XCTUnwrap(TimeZone(identifier: "America/New_York"))
        let start = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 3, day: 6, hour: 12)))
        let afterDST = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 3, day: 10, hour: 12)))
        let window = try XCTUnwrap(FertilityWindowCalculator.window(for: afterDST, lastPeriodStart: start, averageCycleLength: 29, lutealPhaseLength: 14, calendar: calendar))
        XCTAssertEqual(window.cycleDay, 5)
    }

    func testProjectionRollsAcrossLeapDay() throws {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(secondsFromGMT: 0)!
        let start = try XCTUnwrap(calendar.date(from: DateComponents(year: 2028, month: 2, day: 1)))
        let march = try XCTUnwrap(calendar.date(from: DateComponents(year: 2028, month: 3, day: 2)))
        let window = try XCTUnwrap(FertilityWindowCalculator.window(for: march, lastPeriodStart: start, averageCycleLength: 29, lutealPhaseLength: 14, projectsFutureCycles: true, calendar: calendar))
        XCTAssertTrue(calendar.isDate(window.cycleStart, inSameDayAs: try XCTUnwrap(calendar.date(from: DateComponents(year: 2028, month: 3, day: 1)))))
        XCTAssertEqual(window.cycleDay, 2)
    }

    func testLearnedAverageIgnoresImplausibleIntervals() throws {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(secondsFromGMT: 0)!
        let starts = try [
            DateComponents(year: 2026, month: 1, day: 1),
            DateComponents(year: 2026, month: 1, day: 30),
            DateComponents(year: 2026, month: 2, day: 28),
            DateComponents(year: 2026, month: 5, day: 30)
        ].map { try XCTUnwrap(calendar.date(from: $0)) }
        XCTAssertEqual(CycleTrackingService.learnedAverageCycleLength(from: starts.map { PeriodEvent(startDate: $0) }, fallback: 28, calendar: calendar), 29)
    }

    func testActualSecondCycleStartReplacesTheEarlierEstimate() throws {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(secondsFromGMT: 0)!
        let firstPeriod = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 5, day: 1)))
        let actualSecondPeriod = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 5, day: 31)))
        let today = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 6, day: 2)))

        let estimated = try XCTUnwrap(FertilityWindowCalculator.window(
            for: today,
            lastPeriodStart: firstPeriod,
            averageCycleLength: 28,
            lutealPhaseLength: 14,
            calendar: calendar
        ))
        XCTAssertTrue(calendar.isDate(estimated.cycleStart, inSameDayAs: firstPeriod))
        XCTAssertEqual(estimated.cycleDay, 33)

        let corrected = try XCTUnwrap(FertilityWindowCalculator.window(
            for: today,
            lastPeriodStart: actualSecondPeriod,
            averageCycleLength: 28,
            lutealPhaseLength: 14,
            calendar: calendar
        ))
        XCTAssertTrue(calendar.isDate(corrected.cycleStart, inSameDayAs: actualSecondPeriod))
        XCTAssertEqual(corrected.cycleDay, 3)
        XCTAssertTrue(calendar.isDate(corrected.predictedOvulationDate, inSameDayAs: try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 6, day: 13)))))
    }

    func testCycleRecordsPreserveIrregularThreeMonthHistory() throws {
        let calendar = Calendar.current
        let starts = try [
            DateComponents(year: 2026, month: 8, day: 3, hour: 12),
            DateComponents(year: 2026, month: 9, day: 1, hour: 12),
            DateComponents(year: 2026, month: 9, day: 28, hour: 12),
            DateComponents(year: 2026, month: 10, day: 30, hour: 12)
        ].map { try XCTUnwrap(calendar.date(from: $0)) }
        let periods = starts.map { PeriodEvent(startDate: $0) }

        XCTAssertEqual(CycleTrackingService.learnedAverageCycleLength(from: periods, fallback: 28, calendar: calendar), 29)

        let records = zip(starts, starts.dropFirst()).map { start, end in
            CycleRecord(startDate: start, endDate: end, status: .completed)
        } + [CycleRecord(startDate: starts.last!, status: .active)]
        let september = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 15, hour: 12)))
        XCTAssertTrue(calendar.isDate(try XCTUnwrap(CycleTrackingService.cycle(containing: september, records: records, calendar: calendar)).startDate, inSameDayAs: starts[1]))
    }

    func testPredictedOvulationUpdateMovesDependentWindowDates() throws {
        // SwiftData model initializers normalize dates with Calendar.current.
        let calendar = Calendar.current
        let cycleStart = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 8, day: 3)))
        let today = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 8, day: 6)))
        let updatedOvulation = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 8, day: 13)))
        let cycle = CycleRecord(
            startDate: cycleStart,
            predictedOvulationDate: updatedOvulation,
            ovulationSource: .testSupported,
            averageCycleLengthAtStart: 28,
            lutealPhaseLengthAtStart: 14
        )

        let window = try XCTUnwrap(CycleTrackingService.window(for: today, records: [cycle], settings: nil, calendar: calendar))

        XCTAssertTrue(calendar.isDate(window.predictedOvulationDate, inSameDayAs: updatedOvulation))
        XCTAssertTrue(calendar.isDate(window.fertileStartDate, inSameDayAs: try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 8, day: 8)))))
        XCTAssertTrue(calendar.isDate(window.fertileEndDate, inSameDayAs: updatedOvulation))
        XCTAssertTrue(calendar.isDate(window.opkStartDate, inSameDayAs: try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 8, day: 6)))))
    }

    func testLutealPhaseLearnsOnlyFromObservedOvulation() throws {
        let calendar = Calendar(identifier: .gregorian)
        let start = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 1, day: 1)))
        let ovulation = try XCTUnwrap(calendar.date(byAdding: .day, value: 15, to: start))
        let nextPeriod = try XCTUnwrap(calendar.date(byAdding: .day, value: 28, to: start))
        let observed = CycleRecord(startDate: start, endDate: nextPeriod, confirmedOvulationDate: ovulation, ovulationSource: .userConfirmed)
        let predictionOnly = CycleRecord(startDate: nextPeriod, endDate: calendar.date(byAdding: .day, value: 30, to: nextPeriod), predictedOvulationDate: calendar.date(byAdding: .day, value: 10, to: nextPeriod))

        // Ovulation on offset 15, next period offset 28: 12 days strictly between.
        XCTAssertEqual(CycleTrackingService.learnedLutealPhaseLength(from: [observed, predictionOnly], fallback: 14, calendar: calendar), 12)
    }

    // MARK: Luteal convention, period length, hand-set lengths

    func testLearnedLutealRoundTripsThroughCalculator() throws {
        let calendar = Calendar.current
        let start = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 1, day: 1)))
        let window = try XCTUnwrap(FertilityWindowCalculator.window(for: start, lastPeriodStart: start, averageCycleLength: 30, lutealPhaseLength: 13, calendar: calendar))
        let cycle = CycleRecord(startDate: start, endDate: window.nextPeriodDate, confirmedOvulationDate: window.predictedOvulationDate, ovulationSource: .userConfirmed)
        XCTAssertEqual(CycleTrackingService.learnedLutealPhaseLength(from: [cycle], fallback: 14, calendar: calendar), 13)
    }

    func testHandSetCycleLengthBeatsLearnedHistory() throws {
        let calendar = Calendar.current
        func day(_ month: Int, _ day: Int) throws -> Date { try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: month, day: day))) }
        // History says 28 days.
        let periods = [PeriodEvent(startDate: try day(6, 8)), PeriodEvent(startDate: try day(7, 6)), PeriodEvent(startDate: try day(8, 3))]
        let cycle = CycleRecord(startDate: try day(8, 3), averageCycleLengthAtStart: 28, lutealPhaseLengthAtStart: 14)
        let learned = try XCTUnwrap(CycleTrackingService.window(for: try day(8, 10), records: [cycle], periods: periods, settings: nil, calendar: calendar))
        XCTAssertTrue(calendar.isDate(learned.nextPeriodDate, inSameDayAs: try day(8, 31)))

        cycle.userSetCycleLength = 33
        let handSet = try XCTUnwrap(CycleTrackingService.window(for: try day(8, 10), records: [cycle], periods: periods, settings: nil, calendar: calendar))
        XCTAssertTrue(calendar.isDate(handSet.nextPeriodDate, inSameDayAs: try day(9, 5)))
    }

    func testPeriodLengthLearnsFromEndedPeriodsOnly() throws {
        let calendar = Calendar.current
        func day(_ month: Int, _ day: Int) throws -> Date { try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: month, day: day))) }
        let periods = [
            PeriodEvent(startDate: try day(6, 1), endDate: try day(6, 3)),   // 3 days
            PeriodEvent(startDate: try day(7, 1), endDate: try day(7, 4)),   // 4 days
            PeriodEvent(startDate: try day(8, 1)),                           // open-ended: ignored
            PeriodEvent(startDate: try day(9, 1), endDate: try day(9, 4))    // 4 days
        ]
        XCTAssertEqual(CycleTrackingService.learnedPeriodLength(from: periods, fallback: 6, calendar: calendar), 4)
        XCTAssertEqual(CycleTrackingService.learnedPeriodLength(from: [PeriodEvent(startDate: try day(8, 1))], fallback: 6, calendar: calendar), 6)
    }

    func testForecastPeriodUsesPeriodLength() throws {
        let calendar = Calendar.current
        let start = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 1)))
        let window = try XCTUnwrap(FertilityWindowCalculator.window(for: start, lastPeriodStart: start, averageCycleLength: 28, lutealPhaseLength: 14, periodLength: 3, calendar: calendar))
        let third = try XCTUnwrap(calendar.date(byAdding: .day, value: 2, to: window.nextPeriodDate))
        let fourth = try XCTUnwrap(calendar.date(byAdding: .day, value: 3, to: window.nextPeriodDate))
        XCTAssertEqual(CycleCalendarPhaseResolver.phase(for: third, window: window, cycleRecords: [], periodEvents: [], calendar: calendar), .predictedPeriod)
        XCTAssertNotEqual(CycleCalendarPhaseResolver.phase(for: fourth, window: window, cycleRecords: [], periodEvents: [], calendar: calendar), .predictedPeriod)
    }

    func testCycleLengthVariabilityRequiresAtLeastThreeIntervals() throws {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(secondsFromGMT: 0)!
        let starts = try [
            DateComponents(year: 2026, month: 1, day: 1),
            DateComponents(year: 2026, month: 1, day: 29),
            DateComponents(year: 2026, month: 2, day: 26)
        ].map { try XCTUnwrap(calendar.date(from: $0)) }
        XCTAssertNil(CycleTrackingService.cycleLengthVariability(from: starts.map { PeriodEvent(startDate: $0) }, calendar: calendar))
    }

    func testCycleLengthVariabilityIsSpreadOfRecentLengths() throws {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(secondsFromGMT: 0)!
        let starts = try [
            DateComponents(year: 2026, month: 1, day: 1),
            DateComponents(year: 2026, month: 1, day: 25),  // 24
            DateComponents(year: 2026, month: 2, day: 22),  // 28
            DateComponents(year: 2026, month: 3, day: 26)   // 32
        ].map { try XCTUnwrap(calendar.date(from: $0)) }
        XCTAssertEqual(CycleTrackingService.cycleLengthVariability(from: starts.map { PeriodEvent(startDate: $0) }, calendar: calendar), 8)
    }

    func testIrregularCyclesWidenTheTestingWindow() throws {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(secondsFromGMT: 0)!
        let start = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 5, day: 1)))
        let today = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 5, day: 10)))

        let steady = try XCTUnwrap(FertilityWindowCalculator.window(for: today, lastPeriodStart: start, averageCycleLength: 28, lutealPhaseLength: 14, calendar: calendar))
        XCTAssertFalse(steady.isIrregular)

        let irregular = try XCTUnwrap(FertilityWindowCalculator.window(for: today, lastPeriodStart: start, averageCycleLength: 28, lutealPhaseLength: 14, cycleLengthVariabilityDays: 10, calendar: calendar))
        XCTAssertTrue(irregular.isIrregular)
        // Widened by min(5, 10/2) = 5 days, but the early side stops at the
        // day after the period (cycle day 6 with a 5-day period) so it never
        // contradicts the period days drawn on the calendar.
        let dayAfterPeriod = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 5, day: 6)))
        XCTAssertEqual(irregular.fertileStartDate, dayAfterPeriod)
        XCTAssertEqual(calendar.dateComponents([.day], from: steady.fertileEndDate, to: irregular.fertileEndDate).day, 5)
        XCTAssertEqual(irregular.opkStartDate, dayAfterPeriod)
        XCTAssertLessThan(irregular.fertileStartDate, steady.fertileStartDate)
        // Ovulation/period dates themselves are estimates of a single day and
        // stay put - only the start of the testing window moves earlier.
        XCTAssertEqual(irregular.predictedOvulationDate, steady.predictedOvulationDate)
        XCTAssertEqual(irregular.nextPeriodDate, steady.nextPeriodDate)
    }

    func testHighlyIrregularCyclesWidenUpToTheLargerCap() throws {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(secondsFromGMT: 0)!
        let start = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 5, day: 1)))
        let today = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 5, day: 10)))

        // A large variability (24 days) would ask for min(cap, 24/2)=12 days
        // of padding; the cap (10) should win rather than the old 5-day cap.
        let veryIrregular = try XCTUnwrap(FertilityWindowCalculator.window(for: today, lastPeriodStart: start, averageCycleLength: 28, lutealPhaseLength: 14, cycleLengthVariabilityDays: 24, calendar: calendar))

        XCTAssertTrue(veryIrregular.isIrregular)
        XCTAssertEqual(FertilityWindowCalculator.irregularityPaddingCapDays, 10)
        let dayAfterPeriod = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 5, day: 6)))
        XCTAssertEqual(veryIrregular.fertileStartDate, dayAfterPeriod, "Widening stops at the day after the period")
        XCTAssertEqual(veryIrregular.opkStartDate, dayAfterPeriod)
    }

    func testModeratelyVariableCyclesDoNotWidenTheWindow() throws {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(secondsFromGMT: 0)!
        let start = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 5, day: 1)))
        let today = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 5, day: 10)))

        let steady = try XCTUnwrap(FertilityWindowCalculator.window(for: today, lastPeriodStart: start, averageCycleLength: 28, lutealPhaseLength: 14, calendar: calendar))
        let belowThreshold = try XCTUnwrap(FertilityWindowCalculator.window(for: today, lastPeriodStart: start, averageCycleLength: 28, lutealPhaseLength: 14, cycleLengthVariabilityDays: 7, calendar: calendar))

        XCTAssertFalse(belowThreshold.isIrregular)
        XCTAssertEqual(belowThreshold.fertileStartDate, steady.fertileStartDate)
        XCTAssertEqual(belowThreshold.opkStartDate, steady.opkStartDate)
    }

    func testCalendarKeepsLoggedPeriodAboveFertilityPredictions() throws {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(secondsFromGMT: 0)!
        let cycleStart = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 2)))
        let date = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 3)))
        let ovulation = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 4)))
        let window = FertilityWindow(
            cycleStart: cycleStart,
            cycleDay: 2,
            predictedOvulationDate: ovulation,
            fertileStartDate: try XCTUnwrap(calendar.date(byAdding: .day, value: -5, to: ovulation)),
            fertileEndDate: ovulation,
            opkStartDate: try XCTUnwrap(calendar.date(byAdding: .day, value: -7, to: ovulation)),
            nextPeriodDate: try XCTUnwrap(calendar.date(byAdding: .day, value: 14, to: ovulation))
        )

        XCTAssertEqual(CycleCalendarPhaseResolver.phase(for: date, window: window, cycleRecords: [], periodEvents: [PeriodEvent(startDate: cycleStart)], calendar: calendar), .period)
    }

    func testCalendarShowsExpectedPeriodWhenThereIsNoHigherPriorityState() throws {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(secondsFromGMT: 0)!
        let cycleStart = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 1)))
        let ovulation = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 14)))
        let window = FertilityWindow(
            cycleStart: cycleStart,
            cycleDay: 2,
            predictedOvulationDate: ovulation,
            fertileStartDate: try XCTUnwrap(calendar.date(byAdding: .day, value: -5, to: ovulation)),
            fertileEndDate: ovulation,
            opkStartDate: try XCTUnwrap(calendar.date(byAdding: .day, value: -7, to: ovulation)),
            nextPeriodDate: try XCTUnwrap(calendar.date(byAdding: .day, value: 14, to: ovulation))
        )
        let expectedPeriodDay = window.nextPeriodDate

        XCTAssertEqual(CycleCalendarPhaseResolver.phase(for: expectedPeriodDay, window: window, cycleRecords: [], periodEvents: [], calendar: calendar), .predictedPeriod)
    }

    func testStalePredictedOvulationDoesNotOverrideANewCycle() throws {
        // SwiftData model initializers normalize dates with Calendar.current.
        let calendar = Calendar.current
        let cycleStart = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 2)))
        let staleOvulation = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 4)))
        let date = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 3)))
        let cycle = CycleRecord(
            startDate: cycleStart,
            predictedOvulationDate: staleOvulation,
            expectedPeriodDate: try XCTUnwrap(calendar.date(byAdding: .day, value: 14, to: staleOvulation)),
            averageCycleLengthAtStart: 28,
            lutealPhaseLengthAtStart: 14
        )

        let window = try XCTUnwrap(CycleTrackingService.window(for: date, records: [cycle], settings: nil, calendar: calendar))

        XCTAssertTrue(calendar.isDate(window.predictedOvulationDate, inSameDayAs: try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 15)))))
        XCTAssertTrue(calendar.isDate(window.nextPeriodDate, inSameDayAs: try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 30)))))
    }

    func testConfirmedPeriodEndStopsExpectedPeriodStyling() throws {
        // SwiftData model initializers normalize dates with Calendar.current.
        let calendar = Calendar.current
        let start = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 1)))
        let end = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 4)))
        let afterEnd = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 5)))
        let window = FertilityWindow(
            cycleStart: start,
            cycleDay: 5,
            predictedOvulationDate: try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 15))),
            fertileStartDate: try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 10))),
            fertileEndDate: try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 15))),
            opkStartDate: try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 8))),
            nextPeriodDate: try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 29)))
        )

        XCTAssertEqual(CycleCalendarPhaseResolver.phase(for: afterEnd, window: window, cycleRecords: [], periodEvents: [PeriodEvent(startDate: start, endDate: end)], calendar: calendar), .regular)
    }

    func testEditingAnExistingCyclesLengthAssumptionsChangesItsWindow() throws {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(secondsFromGMT: 0)!
        let start = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 8, day: 3)))
        let cycle = CycleRecord(startDate: start, averageCycleLengthAtStart: 28, lutealPhaseLengthAtStart: 14)

        let before = try XCTUnwrap(CycleTrackingService.window(records: [cycle], settings: nil, calendar: calendar))

        // Mirrors what CycleRecordEditor.save() does when the user edits this
        // specific cycle's length assumptions after the fact, rather than
        // only being able to change the global default for future cycles.
        cycle.averageCycleLengthAtStart = 32
        cycle.lutealPhaseLengthAtStart = 12

        let after = try XCTUnwrap(CycleTrackingService.window(records: [cycle], settings: nil, calendar: calendar))

        XCTAssertNotEqual(before.predictedOvulationDate, after.predictedOvulationDate)
        XCTAssertNotEqual(before.nextPeriodDate, after.nextPeriodDate)
    }

    func testPeriodCanBeEditedFromAnyDayItCovers() throws {
        // SwiftData model initializers normalize dates with Calendar.current.
        let calendar = Calendar.current
        let start = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 1)))
        let end = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 4)))
        let selectedDay = try XCTUnwrap(calendar.date(from: DateComponents(year: 2026, month: 9, day: 4)))
        let period = PeriodEvent(startDate: start, endDate: end)

        XCTAssertEqual(CycleTrackingService.periodEvent(containing: selectedDay, in: [period], calendar: calendar)?.id, period.id)
    }
}
