import Foundation
import SwiftData

enum PeriodCheckInCopy {
    static let title = "Did your period start?"
    static let titleWithTest = "Did your period start? If not, consider a test"
}

enum OvulationReminderCopy {
    static let startTitle = "Ready to start ovulation testing?"
    static let fertileTitle = "Your fertile days may be starting"
    static let peakTitle = "Ovulation may be getting closer"
    static let followUpTitle = "Still waiting for a peak?"
    static let highResultTitle = "Your LH result was high — want to check again?"
}

/// Turns a computed FertilityWindow into standing Reminder rows, opt-in via
/// UserSettings.autoRemindersEnabled. Only ever touches reminders it created
/// itself (Reminder.isAutoGenerated) so a user's own custom reminders on the
/// same cycle are never overwritten or duplicated.
enum ReminderAutomationService {
    /// Resolve persisted history at refresh time, using the calendar's resolver.
    /// This repairs saved reminders even when the calendar tab is never opened.
    @MainActor
    static func syncCurrentPredictions(
        settings: UserSettings,
        context: ModelContext,
        calendar: Calendar = .current,
        now: Date = .now
    ) async {
        guard let records = try? context.fetch(FetchDescriptor<CycleRecord>()),
              let periods = try? context.fetch(FetchDescriptor<PeriodEvent>()),
              let reminders = try? context.fetch(FetchDescriptor<Reminder>()) else { return }
        guard let cycle = CycleTrackingService.activeCycle(on: now, records: records, calendar: calendar),
              let window = CycleTrackingService.window(for: now, records: records, periods: periods, settings: settings, calendar: calendar) else {
            removeAutoReminders(reminders, context: context)
            return
        }
        await syncPredictedReminders(
            cycle: cycle, window: window, settings: settings,
            existingReminders: reminders, context: context, calendar: calendar, now: now
        )
    }

    @MainActor
    static func syncPredictedReminders(
        cycle: CycleRecord,
        window: FertilityWindow,
        settings: UserSettings,
        existingReminders: [Reminder],
        context: ModelContext,
        calendar: Calendar = .current,
        now: Date = .now
    ) async {
        guard settings.autoRemindersEnabled else {
            removeAutoReminders(existingReminders, context: context)
            return
        }
        let today = calendar.startOfDay(for: now)
        let notificationService = NotificationService()
        let isAuthorized = await notificationService.isAuthorized()
        guard !Task.isCancelled else { return }
        // Another sync can finish while notification authorization is read.
        // Refresh the rows so overlapping view/save tasks cannot insert duplicates.
        let existingReminders = (try? context.fetch(FetchDescriptor<Reminder>())) ?? existingReminders

        // Irregular cycles get a genuinely wider testing window (see
        // FertilityWindowCalculator.irregularityPaddingCapDays), so a single
        // ovulation-test reminder on the earliest possible day isn't enough -
        // add a mid-window nudge to keep testing through the whole estimate
        // rather than implying one precise day is the only one that matters.
        let hasOvulationEvidence = cycle.confirmedOvulationDate != nil || cycle.ovulationSource == .testSupported || cycle.ovulationSource == .temperatureSupported
        // A cycle marked "ended" (including pregnancy loss) should never keep
        // nudging the user to retest for a pregnancy that has already
        // concluded - that reminder type is suppressed entirely rather than
        // just skipped for one sync, so an already-scheduled one is cancelled
        // below via the existing managedTypes/targetTypes cleanup.
        let pregnancyHasEnded = cycle.pregnancyState == .ended
        let canTrackOvulation = cycle.pregnancyState == .trying || cycle.pregnancyState == .periodArrived
        // In pregnancy mode there's no period to expect or test for - keep
        // every cycle nudge quiet until the person leaves that mode.
        let isPregnant = cycle.pregnancyState == .confirmedPregnant
        var candidates: [(ReminderType, Bool, Date, String)] = [
            (.ovulationTest, settings.autoOvulationTestRemindersEnabled && !hasOvulationEvidence && canTrackOvulation, window.opkStartDate, OvulationReminderCopy.startTitle),
            (.fertileWindow, settings.autoFertileWindowRemindersEnabled && !hasOvulationEvidence && canTrackOvulation, window.fertileStartDate, OvulationReminderCopy.fertileTitle),
            (.fertilePeak, settings.autoFertilePeakRemindersEnabled && !hasOvulationEvidence && canTrackOvulation, window.predictedOvulationDate, OvulationReminderCopy.peakTitle),
            (.periodExpected, settings.autoPeriodExpectedRemindersEnabled && !isPregnant, calendar.date(byAdding: .day, value: -1, to: window.nextPeriodDate) ?? window.nextPeriodDate, "Period may start soon"),
            (.periodCheckIn, settings.autoPeriodCheckInRemindersEnabled && !isPregnant, window.nextPeriodDate, settings.autoPregnancyRetestRemindersEnabled ? PeriodCheckInCopy.titleWithTest : PeriodCheckInCopy.title),
            // The home card checks in daily. One later optional notification
            // is more useful than repeating it two days after the estimate.
            (.periodLate, settings.autoPeriodLateRemindersEnabled && !pregnancyHasEnded && !isPregnant, calendar.date(byAdding: .day, value: (window.isIrregular || window.profileWidening == .pcos || window.profileWidening == .irregularPeriods) ? 14 : 7, to: window.nextPeriodDate) ?? window.nextPeriodDate, "Still waiting for your period?"),
            // The due-day check-in already covers testing if bleeding has not
            // started. Never schedule a second alert at the same time for it.
            (.pregnancyRetest, settings.autoPregnancyRetestRemindersEnabled && !settings.autoPeriodCheckInRemindersEnabled && !pregnancyHasEnded && !isPregnant, window.nextPeriodDate, "Consider a pregnancy test")
        ]
        if window.isIrregular || window.profileWidening != nil, settings.autoOvulationTestRemindersEnabled, !hasOvulationEvidence, canTrackOvulation {
            let midpointDays = calendar.dateComponents([.day], from: window.opkStartDate, to: window.fertileEndDate).day.map { $0 / 2 } ?? 0
            let midpointDate = calendar.date(byAdding: .day, value: midpointDays, to: window.opkStartDate) ?? window.fertileStartDate
            let overlapsOtherNudge = candidates.prefix(3).contains {
                $0.1 && calendar.isDate($0.2, inSameDayAs: midpointDate)
            }
            if midpointDate > window.opkStartDate && !overlapsOtherNudge {
                candidates.append((.ovulationFollowUp, true, midpointDate, OvulationReminderCopy.followUpTitle))
            }
        }
        // A saved result is better evidence than a calendar estimate. Only
        // the newest valid result can prompt a follow-up; a subsequent Low,
        // Peak, invalid, or excluded test cancels this suggestion. Waiting a
        // full day avoids imposing a kit-independent eight-hour schedule.
        if settings.autoOvulationTestRemindersEnabled, !hasOvulationEvidence, canTrackOvulation,
           let scans = try? context.fetch(FetchDescriptor<Scan>()),
           let latest = scans.filter({
               $0.testType == .ovulation && $0.cycleRecordID == cycle.id &&
               $0.createdAt >= cycle.startDate && $0.createdAt <= now
           }).max(by: { $0.createdAt < $1.createdAt }),
           !latest.excludedFromCalculations,
           latest.controlLineDetected,
           [.high, .rising].contains(latest.resultType),
           now.timeIntervalSince(latest.createdAt) < 24 * 60 * 60,
           let followUpDate = calendar.date(byAdding: .day, value: 1, to: latest.createdAt) {
            candidates.removeAll { $0.0 == .ovulationFollowUp }
            candidates.append((.ovulationFollowUp, true, followUpDate, OvulationReminderCopy.highResultTitle))
        }
        let targets = candidates.filter { $0.1 && calendar.startOfDay(for: $0.2) >= today && cycle.endDate == nil }.map { ($0.0, $0.2, $0.3) }
        let targetTypes = Set(targets.map(\.0))
        // Retire the old generic body-check-in used for irregular-cycle testing.
        // Only automatic rows are touched; personal body check-ins remain intact.
        let managedTypes = Set(candidates.map(\.0)).union([.ovulationFollowUp, .bodyCheckIn])

        // Remove obsolete future reminders even if the replacement date is
        // already past. Skipping that date first leaves the old nudge alive.
        for reminder in existingReminders where reminder.isAutoGenerated && (
            (reminder.cycleRecordID == cycle.id && managedTypes.contains(reminder.reminderType) && !targetTypes.contains(reminder.reminderType)) ||
            (cycle.endDate == nil && reminder.cycleRecordID != cycle.id && !reminder.isCompleted && reminder.scheduledDate >= today)
        ) {
            notificationService.cancel(id: reminder.id)
            context.delete(reminder)
        }

        for (type, date, title) in targets {
            // A reminder for a day that's already passed isn't useful; skip
            // it rather than firing a notification in the past.
            guard calendar.startOfDay(for: date) >= today else { continue }
            let notifyDate = type == .ovulationFollowUp && title == OvulationReminderCopy.highResultTitle
                ? date
                : (calendar.date(bySettingHour: 9, minute: 0, second: 0, of: date) ?? date)

            // Scheduling yields between types, so read again before each
            // upsert and collapse older duplicates of this automatic reminder.
            let latestReminders = (try? context.fetch(FetchDescriptor<Reminder>())) ?? existingReminders
            let matches = latestReminders.filter {
                $0.isAutoGenerated && $0.cycleRecordID == cycle.id && $0.reminderType == type
            }
            for duplicate in matches.dropFirst() {
                notificationService.cancel(id: duplicate.id)
                context.delete(duplicate)
            }
            if let existing = matches.first {
                guard existing.scheduledDate != notifyDate || existing.title != title else { continue }
                notificationService.cancel(id: existing.id)
                existing.title = title
                existing.scheduledDate = notifyDate
                existing.isCompleted = false
                existing.completedAt = nil
                if isAuthorized {
                    try? await notificationService.schedule(ReminderNotification(reminder: existing))
                }
            } else {
                let reminder = Reminder(title: title, reminderType: type, scheduledDate: notifyDate, cycleRecordID: cycle.id, isAutoGenerated: true)
                context.insert(reminder)
                if isAuthorized {
                    try? await notificationService.schedule(ReminderNotification(reminder: reminder))
                }
            }
        }
        try? context.save()
    }

    @MainActor
    private static func removeAutoReminders(_ reminders: [Reminder], context: ModelContext) {
        let service = NotificationService()
        for reminder in reminders where reminder.isAutoGenerated {
            service.cancel(id: reminder.id)
            context.delete(reminder)
        }
        try? context.save()
    }
}
